services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
volumes:
  dynamodb:
