name: Container Deploy
description: ECSサービスを更新し、コンテナをデプロイします。
inputs:
  ecs-cluster:
    required: true
    description: ECSクラスター
  ecs-service:
    required: true
    description: ECSサービス
  task-definition:
    required: true
    description: タスク定義
  container-name:
    required: true
    description: コンテナ名
  container-image:
    required: true
    description: コンテナイメージ
  codedeploy-application:
    required: true
    description: CodeDeployアプリケーション
  codedeploy-deploygroup:
    required: true
    description: CodeDeployデプロイグループ
runs:
  using: composite
  steps:
    # タスク定義をGithub Hosted Runnerにて取得（ファイル名：task-def.json）
    - run: |
        aws ecs describe-task-definition --task-definition "${TASK_DEFINITION}" \
        --query taskDefinition --output json > "${RUNNER_TEMP}/task-def.json"
      env:
        TASK_DEFINITION: ${{ inputs.task-definition }}
      shell: bash

    # Github Hosted Runnerにて取得したタスク定義（task-def.json）におけるコンテナイメージURIを更新する
    # task-definitionで更新するタスク定義ファイルを指定・container-nameで更新するコンテナ名を指定・imageでコンテナイメージURIを指定
    - uses: aws-actions/amazon-ecs-render-task-definition@v1
      id: render
      with:
        task-definition: ${{ runner.temp }}/task-def.json
        container-name: ${{ inputs.container-name }}
        image: ${{ inputs.container-image }}

    # ローカルで更新したタスク定義をAWS上に登録し、そのタスク定義を使用してECSサービスを更新する
    - uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: ${{ inputs.ecs-cluster }}
        service: ${{ inputs.ecs-service }}
        task-definition: ${{ steps.render.outputs.task-definition }}
        wait-for-service-stability: true
        codedeploy-appspec: appspec.yml
        codedeploy-application: ${{ inputs.codedeploy-application }}
        codedeploy-deployment-group: ${{ inputs.codedeploy-deploygroup }}
